### ISSUE TITLE
slave process manage support

### ISSUE THREAD

**Issue by luckydrq** [node-modules/cfork#12]
Sometimes in my project i need to fork additional processes to do  some certain job. So i think maybe `cfork` can help me to manage these slave processes in the similar way as it does to its worker processes. Here is my thoughts:

```js
cfork({
  exec: workerPath,
  args: workerArgs,
  slaves: [slave1Path, slave2Path...]
});
```

I want to hear your thoughts. If this feature is approved, i'm pleasure to submit a PR.

**Comment by fengmk2** [comment]
do it!
